# Generated by Django 2.0.4 on 2018-04-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('benchmark', models.CharField(max_length=200)),
                ('management_expense_ratio', models.FloatField()),
                ('admission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='security_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityType'),
        ),
    ]
