# Generated by Django 2.0.4 on 2018-05-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'notetypes',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateField()),
                ('date_first_trade', models.DateField()),
                ('expected_standard_deviation', models.FloatField()),
                ('expected_annual_return', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('skewness', models.FloatField()),
                ('kurtosis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Portfolio')),
            ],
            options={
                'verbose_name_plural': 'portfoliosecurities',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('benchmark', models.CharField(blank=True, max_length=200, null=True)),
                ('management_expense_ratio', models.FloatField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('fetch_data', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'securities',
            },
        ),
        migrations.CreateModel(
            name='SecurityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField()),
                ('payable_date', models.DateField(blank=True, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('dividend_per_share', models.FloatField()),
                ('franking_percentage', models.FloatField(blank=True, null=True)),
                ('divident_type', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security')),
            ],
            options={
                'verbose_name_plural': 'dividends',
            },
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200)),
                ('setting_text_value', models.CharField(blank=True, max_length=200)),
                ('setting_numerical_value', models.FloatField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SettingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='setting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SettingType'),
        ),
        migrations.AddField(
            model_name='security',
            name='security_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityClass'),
        ),
        migrations.AddField(
            model_name='security',
            name='security_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityType'),
        ),
        migrations.AddField(
            model_name='portfoliosecurity',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.NoteTypes'),
        ),
        migrations.AddField(
            model_name='note',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security'),
        ),
        migrations.AddField(
            model_name='note',
            name='security_daily_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityDailyPrice'),
        ),
    ]
