# Generated by Django 2.0.4 on 2018-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitydividend',
            old_name='divident_type',
            new_name='dividend_type',
        ),
    ]
