# Generated by Django 2.0.4 on 2018-04-29 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateField()),
                ('date_first_trade', models.DateField()),
                ('expected_standard_deviation', models.FloatField()),
                ('expected_annual_return', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('skewness', models.FloatField()),
                ('kurtosis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField()),
                ('dividend_per_share', models.FloatField()),
                ('franking_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200)),
                ('setting_text_value', models.CharField(max_length=200)),
                ('setting_numerical_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='fetch_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='setting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SettingType'),
        ),
        migrations.AddField(
            model_name='securitydailyprice',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security'),
        ),
        migrations.AddField(
            model_name='portfoliosecurity',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.NoteTypes'),
        ),
        migrations.AddField(
            model_name='note',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security'),
        ),
        migrations.AddField(
            model_name='note',
            name='security_daily_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityDailyPrice'),
        ),
    ]
