# Generated by Django 2.0.4 on 2018-04-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0003_auto_20180429_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydividend',
            name='security',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datamanager.Security'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='admission_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='benchmark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='security',
            name='management_expense_ratio',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='security_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityClass'),
        ),
    ]
