# Generated by Django 2.0.4 on 2018-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0003_auto_20180513_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydividend',
            name='dividend_type',
            field=models.CharField(max_length=20),
        ),
    ]
