# Generated by Django 2.0.4 on 2018-05-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0004_auto_20180430_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='security_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityClass'),
        ),
        migrations.AlterField(
            model_name='security',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
