# Generated by Django 2.0.4 on 2018-05-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0005_auto_20180502_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='benchmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='management_expense_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='security_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityClass'),
        ),
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datamanager.SecurityType'),
        ),
    ]
